name: CID/X Setup
description: Installs the binaries for usage in subsequent actions
inputs:
  version:
    description: Version
    required: true
    default: v0.4.1
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/setup.sh "${{ inputs.version }}"
      shell: bash
branding:
  icon: code
  color: orange
