name: CID/X Setup
description: Installs the CID/X CLI
inputs:
  version:
    description: Version
    required: true
    default: latest
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/setup.sh "${{ inputs.version }}"
      shell: bash
branding:
  icon: code
  color: orange
